### ISSUE TITLE
Migrate from tfenv to tenv 

### ISSUE THREAD

**Issue by kvendingoldo** [vojtechmares/container-images#3]
Hi! I saw that you're using tfenv in this repository. It's a really good tool, but it does not support OpenTofu and Terragrunt. My team designed a successor of tenv that support Terraform, Terragrunt and OpenTofu. It will be a good idea to migrate into it in due to the growing popularity of OpenTofu.
url: https://github.com/tofuutils/tenv

**Comment by vojtechmares** [comment]
Hi @kvendingoldo, thank you for pointing that out. Although I am not going to migrate to tenv or OpenTofu. I disagree with the way the project is governed and recent legal issues with HashiCorp did not help the case.

Thank you for the interest, but I politely disagree with the proposed change.
